spacing         = 1
padding         = 0
hide_ascii      = true
# prefer_small_ascii = true
separator       = "-" 
key_color       = "#Fccf6C"
separator_color = "#71f094"

[custom_ascii]
color           = "#ff5370"
path            = "~/.config/macchina/ascii/tux"

[palette]
type            = "Light"
glyph           = " "
visible         = false

[bar]
glyph           = "ߋ"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = false

[box]
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[randomize]
key_color       = false
separator_color = false
pool            = "base"

[keys]
de              = "  "
resolution      = "  "
distro          = "  "
kernel          = "  "
shell           = " $ "
packages        = "  "
host            = "  "
battery         = "  "
os              = "  "
wm              = " 缾"
terminal        = "  "
memory          = "  "
machine         = "  "
local_ip        = "  "
backlight       = "  "
cpu             = "  "
cpu_load        = "  "
uptime          = " 神"
