# format = """
# $directory$git_branch
# $character
# """

# Timeout for starship to scan files (in milliseconds).
scan_timeout = 1000

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 700

# Disable the blank line at the start of the prompt
add_newline = false

# TODO: figure out how to create a function that will create a new line 
# for the character only when there are three or more components are visible 
# on the terminal

# format = """
# $directory$git_branch$git_commit$git_state$git_status$package$lua$nodejs$python$character
# """

[directory]
truncation_length = 1
read_only = " "
# truncation_symbol = "…/"
format = "\\[[$path]($style)[$lock_symbol]($lock_style)\\] "
style = "bold red"

[character]
# success_symbol = "[❯](bold yellow)"
# error_symbol = "[✗](bold red)"
# vicmd_symbol = "[❮](bold yellow)"
# success_symbol = "[[>](red)[>](yellow)[>](green)](bold green)"
# error_symbol = "[[>](green)[>](yellow)[>](red)](bold red)"
# vicmd_symbol = "[[>](red)[>](green)[>](yellow)](bold yellow)"
success_symbol = "[↪](bold green)"
error_symbol = "[↪](bold red)"
vicmd_symbol = "[↩](bold yellow)"

[cmd_duration]
format = 'in \[[⏰$duration]($style)\]'

[git_branch]
format = "[\\($symbol$branch\\)]($style) "
symbol = " "
style = "bold yellow"

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖tag "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"
bisect = "[♻️ BISECT](bold  green)"
merge = "[🔀 MERGEING](bold  yellow)"

[git_status]
conflicted = "🚩"
untracked = '[?\($count\)](red)'
modified = '[!\($count\)](yellow)' 
stashed = "🗃️"
staged = '[+\($count\)](green)'
deleted = "${count}🗑️"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[docker_context]
format = "[🐋 $context](blue bold)"

[aws]
symbol = "  "
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\] '

[conda]
symbol = " "
format = '\[[$symbol$environment]($style)\] '

[dart]
symbol = " "
format = '\[[$symbol($version)]($style)\] '

[elixir]
symbol = " "
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\] '

[elm]
symbol = " "
format = '\[[$symbol($version)]($style)\] '

[golang]
symbol = " "
format = '\[[$symbol($version)]($style)\] '

[java]
symbol = " "
format = '\[[$symbol($version)]($style)\] '

[julia]
symbol = " "
format = '\[[$symbol($version)]($style)\] '

[memory_usage]
symbol = " "
format = '\[$symbol[$ram( | $swap)]($style)\] '

[nim]
symbol = " "
format = '\[[$symbol($version)]($style)\] '

[nix_shell]
symbol = " "
format = '\[[$symbol$state( \($name\))]($style)\] '

[package]
symbol = " "
format = '\[[$symbol$version]($style)\] '

[perl]
symbol = " "
format = '\[[$symbol($version)]($style)\] '

[php]
symbol = " "
format = '\[[$symbol($version)]($style)\] '

[python]
symbol = " "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\] '

[ruby]
symbol = " "
format = '\[[$symbol($version)]($style)\] '

[rust]
symbol = " "
format = '\[[$symbol($version)]($style)\] '

[scala]
symbol = " "
format = '\[[$symbol($version)]($style)\] '

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
format = '\[[$symbol($version)]($style)\] '

[cmake]
format = '\[[$symbol($version)]($style)\] '

[crystal]
format = '\[[$symbol($version)]($style)\] '

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\] '

[erlang]
format = '\[[$symbol($version)]($style)\] '

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\] '

[helm]
format = '\[[$symbol($version)]($style)\] '

[kotlin]
format = '\[[$symbol($version)]($style)\] '

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\] '

[lua]
format = '\[[$symbol($version)]($style)\] '

[nodejs]
format = '\[[$symbol($version)]($style)\] '

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\] '

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\] '

[purescript]
format = '\[[$symbol($version)]($style)\] '

[red]
format = '\[[$symbol($version)]($style)\] '

[terraform]
format = '\[[$symbol$workspace]($style)\] '

[time]
format = '\[[$time]($style)\] '

[username]
format = '\[[$user]($style)\] '

[vagrant]
format = '\[[$symbol($version)]($style)\] '

[vlang]
format = '\[[$symbol($version)]($style)\] '

[zig]
format = '\[[$symbol($version)]($style)\] '
